### ISSUE TITLE
Download crash

### ISSUE THREAD

**Issue by SavaletDev** [Zeldown/EMC-Core#1]
Bonjour, 
J'ai un problème. Je code actuellement mon launcher avec électron et j'utilise donc le modules emc-core que je trouve super, mais lors du téléchargement a des moment aléatoire le téléchargement se bloque totalement et ne bouge pas.
[image.png](https://gm1.ggpht.com/b_KIH_i7iPeq83qDNUWQzalEQpdLlHvGKCm25PPiF0aC1c_6eLDf0xi3uf6EviZIMGXc0qcRrYAHnphM3SYCYhRfpbLRsuGB2OtvpUjsfyv8lOIilMOX2BBha3yjZId-Fjh56wLc_eIiqV8NHNyVxCiQLOQOlnBtl4NUmvP57T-ZsBVf9eZNZgd1-JWgn__GNZvKVQE9m-jEr-_Vn634vda4VLej-OJiWVE5Du8houEkcLOgiBLXUNka4xjgR_80lm3wM1gKOtgDYtFEpIU2PDh__13hrlg_KN7Qngys8GMjvpS3Mbb3_j2hplT5ju2NcvAgeY_22tktxtH_N3845NJ0qAuzcmmDtSMJ60XkZ0y5oF74bjejzfPn7DG1JO2B6TsqGSidDN4FFhg522pJpBH2aGizzxmBqsEstAjdqknrUV0RLUhObNiQLpR_zwGoJ6nMeh7SL_0R6apOF9Cx2rlhHA2E9ciklcc_6bUbaSYFI5SC3Jw-A7kdtHFHnFUqPxIktwzonztpj_brpoSCBwwh1BMWdYBKwn54FVbQUNWQLzWOCgdy4Nd4qK3-1oIAUJ0xtWvRJGlYeDtfjzT6N6iu9JU1YHRdT7y94uO6BrzVKGjnkJlyKtCK_MG0y-LJOJ7WSgEvxDFWGMiHd4yJNq0uwegkTeNyaAjTE_-NgCEzB5UfuMJrG3EagjWxbz2R9jdWWUgRCH5Lpm-7G4C37rXTYfqyVaVYxrIr4TN6apDPQPkuCR8XtqvPhfjqzLRx2_4F=s0-l75-ft-l75-ft)
Il n'y a pas d'erreur dans la console : 
[image.png](https://gm1.ggpht.com/QYN2ELZW9NXXEZerODkC0b4dN8iM5FTgQsIbSLIoe7jU90amcSGjGcXHqqiXfja5y8W06QSfzxtNztmsxRICI82q3JOdMwv8AzUChh-Mh6U7OuIq9erEvZqWthKp86cI8yZNuBWnFayHgdeVt_qilXXeEhpIR7Ui_kXRaSWesg6v21SJQfWwfdNNoDuPivsNMGfQRJLTC27wnUI9xfddfm6r1ElFjBo8423omvLFIMKRsays2qjkvsi8bayII923KlB4qn8Ry5ioehcWokeaVfFt2OtS9DoGMhdiMRWPzdKEg8mREB2J32SbFTzvoi-_4_5Hs2gcGWicA8GBYdJe3RtEJvMTweFwhNKpcgiEVkNxRQM-KQzfMxqpSeWiyQ9XGygcEkcpFtK8tszwhFohlD1ksHHIoHeRoyvHVOROsKmAAEXXqwlB4sqi7zw38VZJQMgPwsERfAvUgV6BswIi3cbuU2Z1N8HMs1jcnAV7ENFVR2_4H25u3hZxMNgEGfEIpNya0mwlfaPjVv6dwrabzxufyB8CzG_B_N7K_hVbE143glhHltF9Gl1KyZYKECoD5n6dmMlnoBxKcvZfNvMpIGIcMTTDtlVx6YJhyHq6VowC4sYUDRBu3fllEhUkkaAkBgZXM40VSfJM0Qc-B0ezj0Hv518F0tWfY2XkIGOiqxEqTzqPE0J6Osa9zQSSzAT0UhTnLvGMjOCm3D1LfIaEP3tkrM32_bvgqftboykeToTSRncQIcyC54SLzJa5IaOeB68Avw=s0-l75-ft-l75-ft)

**Comment by Zeldown** [comment]
Bonjour, il m’est impossible d’ouvrir les images que vous avez envoyé :/

pouvez-vous également fournir une copie du code utiliser pour le téléchargement et lancement du jeu ?

merci
